### ISSUE TITLE
Error on version check for vodafone-speedtest: TypeError: Invalid Version: unpublished

### ISSUE THREAD

**Issue by Grothesk242** [peterbaumert/ioBroker.vofo-speedtest#36]
iobroker update is broken

```
echad@chet:~ $ iobroker update
Used repository: live-beta
hash changed or no sources cached => force download of new sources
update done
/opt/iobroker/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: unpublished
    at new SemVer (/opt/iobroker/node_modules/semver/classes/semver.js:38:13)
    at compare (/opt/iobroker/node_modules/semver/functions/compare.js:3:32)
    at Object.gte (/opt/iobroker/node_modules/semver/functions/gte.js:2:30)
    at Object.upToDate (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:152:19)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:244:28
    at Array.forEach (<anonymous>)
    at updateInfo (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:241:30)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupRepo.js:208:37)
    at processImmediate (node:internal/timers:466:21)
```

iobroker.current.log shows: 

```
warn: admin.0 (15022) Error on version check for vodafone-speedtest: TypeError: Invalid Version: unpublished
```

**Versions:**  
 - Adapter version: vodafone-speedtest - v0.0.7
 - JS-Controller version: 3.3.14
 - Node version:  node -v v16.4.0  // npm -v 7.19.0
 - Operating system: Raspberry OS 10 'Buster'

**Comment by Grothesk242** [comment]
Issue is due to the renaming of the adapter. I installed vofo-speedtest from git and now it is working again. Had to update my Echarts data points.

**Comment by peterbaumert** [comment]
Yes sorry, had to rename it due to legal reasons with quite a short deadline. I am currently doing my best to get it published with new name again, Sorry for inconveniences.
