### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mswiege** [peterbaumert/ioBroker.vofo-speedtest#46]
Installation fails on my iobroker instance:

```
$ iobroker add vofo-speedtest auto --host iobroker-pi4

NPM version: 6.14.12

npm install iobroker.vofo-speedtest@0.0.8 --loglevel error --prefix "/opt/iobroker" (System call)

Could not run curl-config, please make sure libcurl dev package is installed.Output: /bin/sh: 1: curl-config: not foundgyp: Call to 'node /opt/iobroker/node_modules/node-libcurl/scripts/curl-config.js --prefix' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack at ChildProcess.emit (events.js:314:20)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)gyp ERR! System Linux 5.10.17-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/opt/iobroker/node_modules/node-libcurl/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"gyp ERR! cwd /opt/iobroker/node_modules/node-libcurlgyp ERR! node -v v12.22.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

node-pre-gyp ERR! build error

node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/opt/iobroker/node_modules/node-libcurl/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

node-pre-gyp ERR! stack at ChildProcess.emit (events.js:314:20)node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1022:16)

node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)node-pre-gyp ERR! System Linux 5.10.17-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/node-libcurlnode-pre-gyp ERR! node -v v12.22.1node-pre-gyp ERR! node-pre-gyp -v v0.15.0

node-pre-gyp ERR! not ok

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! node-libcurl@2.3.3 install: `node-pre-gyp install --fallback-to-build`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the node-libcurl@2.3.3 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR! /home/iobroker/.npm/_logs/2021-07-20T05_59_21_858Z-debug.log

host.iobroker-pi4 Cannot install iobroker.vofo-speedtest@0.0.8: 1

ERROR: Process exited with code 25
```

Platform: linux
Architektur: arm (raspberry 4)
Node.js: v12.22.1 
NPM: 6.14.12

**Comment by peterbaumert** [comment]
"Could not run curl-config, please make sure libcurl dev package is installed.Output:"

curl is a prerequisite to use this adapter. Please install it.

**Comment by mswiege** [comment]
I can do that, but shouldn't the adapter do that in the installation process automatically? I don't think all users are able to do that manually. That's why I added this as a bug.
